### ISSUE TITLE
[Feature] reggae-prompt

### ISSUE THREAD

**Issue by jparrill** [fbac/shell-randomquote#3]
Create a quote file that includes the best reggaeton quotes of the market, use this 'Ya tu sabeh', 'Dale', 'Te kill you la vida brothel' as examples. You can use this videos to get some inspiration:
- https://www.youtube.com/watch?v=KRgmXbeG5z0
- https://www.youtube.com/watch?v=5g0dFrgGil4
- https://www.youtube.com/watch?v=9_OYV8Yr--c

This will make the world a better place for all!

**Comment by fbac** [comment]
Why fucking not. Let's do this.
